#!/usr/bin/env bash

export PLUGIN_COMMAND_PREFIX="generic"
export PLUGIN_SERVICE="generic"
export PLUGIN_DATA_HOST_ROOT="/var/lib/dokku/services/$PLUGIN_SERVICE"
export PLUGIN_DATA_ROOT="$PLUGIN_DATA_HOST_ROOT"
export PLUGIN_AMBASSADOR_IMAGE="${PLUGIN_AMBASSADOR_IMAGE:-dokku/ambassador:0.8.2}"
export PLUGIN_BUSYBOX_IMAGE="${PLUGIN_BUSYBOX_IMAGE:-busybox:1.36}"
export PLUGIN_NETWORK_PREFIX="dokku.generic"
export PLUGIN_CONTAINER_PREFIX="dokku.generic"
export PLUGIN_VOLUME_PREFIX="dokku.generic"
export PLUGIN_STOP_TIMEOUT="${PLUGIN_STOP_TIMEOUT:-10}"
export PLUGIN_RESTART_POLICY="${PLUGIN_RESTART_POLICY:-unless-stopped}"

export DOCKER_BIN="${DOCKER_BIN:-docker}"
