#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"

mkdir -p "$PLUGIN_DATA_HOST_ROOT"
chown dokku:dokku "$PLUGIN_DATA_HOST_ROOT" 2>/dev/null || true

if ! "$DOCKER_BIN" image inspect "$PLUGIN_AMBASSADOR_IMAGE" >/dev/null 2>&1; then
  "$DOCKER_BIN" image pull "$PLUGIN_AMBASSADOR_IMAGE" >/dev/null
fi

if ! "$DOCKER_BIN" image inspect "$PLUGIN_BUSYBOX_IMAGE" >/dev/null 2>&1; then
  "$DOCKER_BIN" image pull "$PLUGIN_BUSYBOX_IMAGE" >/dev/null
fi

echo "dokku-generic plugin installed"
