#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$(cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" && pwd)"
source "$PLUGIN_BASE_PATH/config"
source "$PLUGIN_BASE_PATH/common-functions"
source "$PLUGIN_BASE_PATH/functions"

shift
SERVICE="${1:-}"
[[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
verify_service_name "$SERVICE" || dokku_log_fail "Invalid service name"
service_exists "$SERVICE" || dokku_log_fail "Service $SERVICE does not exist"
acquire_service_lock "$SERVICE"

CONTAINER="$(service_container_name "$SERVICE")"

if service_is_running "$SERVICE"; then
  dokku_log_info1 "Service $SERVICE already running"
  exit 0
fi

if "$DOCKER_BIN" container inspect "$CONTAINER" >/dev/null 2>&1; then
  "$DOCKER_BIN" container start "$CONTAINER" >/dev/null
else
  service_restart_internal "$SERVICE"
fi
dokku_log_info2 "Started $SERVICE"
