#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$(cd "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")" && pwd)"

shift
SERVICE="${1:-}"
IMAGE="${2:-}"

[[ -z "$SERVICE" ]] && { echo " !  Please specify a valid name for the service" >&2; exit 1; }
[[ -z "$IMAGE"   ]] && { echo " !  Please specify a docker image" >&2; exit 1; }

exec "$PLUGIN_BASE_PATH/subcommands/set" "generic:set" "$SERVICE" --image "$IMAGE"
